### ISSUE TITLE
Climate Resources

### ISSUE THREAD

**Issue by WEP11** [WEP11/UNC-Charlotte-Meteorology-Website#5]
We need to know what to add to the climate resources page. Here are some suggestions from the faculty and myself:

Climate Dynamics:
1. NCEI Climate at a Glance
2. CPC ENSO + Oscillations
3. IRI ENSO Forecast Plume

Climatology:
1. HPRCC Climate Summary Maps
2. U.S. Drought Monitor
3. SC-ACIS and XM-ACIS
4. ACIS Web Query Builder
5. CoCoRaHS

Climate Change:
1. NCEI National Climate Report
2. NCEI Climate Extremes Index
3.  ... Everything from the old section I guess

Climate Modeling:
Same, consider the existing resources

**Comment by toadwx** [comment]
First big step in compiling the climate resources list has been taken. All items here (plus a few others) have been added with thumbnails in https://github.com/WEP11/UNC-Charlotte-Meteorology-Website/commit/0032bde83ce431804686aec9dde6129e61d3f57f

Need to determine how much we want to add/remove/reconfigure

**Comment by toadwx** [comment]
Descriptions added in https://github.com/WEP11/UNC-Charlotte-Meteorology-Website/commit/d3ccb299598593ed98ade27c2a7c4b1a4f97dd5a
